### ISSUE TITLE
你好，能开源后端吗？

### ISSUE THREAD

**Issue by 313996337** [dongsuo/vue-data-board#12]
你好，能开源后端吗？

**Comment by dongsuo** [comment]
后端项目的地址是：https://github.com/dongsuo/leancloud-server 
可以参考下面的文档：
https://www.yuque.com/slasher/ys2kwd

**Comment by weituotian** [comment]
@dongsuo 怎么根据业务快速开发，要重新写哪些接口？

**Comment by dongsuo** [comment]
@weituotian emmm……这个跟你们的业务需求有关，由于我这个 demo 严重依赖 leancloud，所以我觉得你应该需要全部重写吧……不过接口其实也不多，主要涉及到用户、数据查询、query 的 CRUD，dashboard 的 CRUD，query 和 dashboard 的关联。我暂时想到的就是这些了。

**Comment by icoreman** [comment]
> @weituotian emmm……这个跟你们的业务需求有关，由于我这个 demo 严重依赖 leancloud，所以我觉得你应该需要全部重写吧……不过接口其实也不多，主要涉及到用户、数据查询、query 的 CRUD，dashboard 的 CRUD，query 和 dashboard 的关联。我暂时想到的就是这些了。

query和dashboard的表结构长什么样呢，mega上分享的只是数据的表及结构吧

**Comment by dongsuo** [comment]
> > @weituotian emmm……这个跟你们的业务需求有关，由于我这个 demo 严重依赖 leancloud，所以我觉得你应该需要全部重写吧……不过接口其实也不多，主要涉及到用户、数据查询、query 的 CRUD，dashboard 的 CRUD，query 和 dashboard 的关联。我暂时想到的就是这些了。
> 
> query和dashboard的表结构长什么样呢，mega上分享的只是数据的表及结构吧

嗯，这个我可以整理一下分享出来

**Comment by dongsuo** [comment]
https://github.com/dongsuo/py_vislib
用 Python 写了一个简单的后端项目，里面有开发数据库的配置，另外文档也更新了一份，在 [docs.vislib.best](https://docs.vislib.best) 可以看到
