### ISSUE TITLE
一个数据多个维度时的柱状图，颜色对应问题

### ISSUE THREAD

**Issue by godchao** [dongsuo/vue-data-board#13]
**当配置一个数据多个维度的柱状图时，相关数据存在，但颜色并没有对应上，柱状只显示了一种颜色。**

<img width="862" alt="github-tongjitu" src="https://user-images.githubusercontent.com/16253163/61602653-082b9f00-ac6d-11e9-8f11-1984d99b6d28.png">

**Comment by dongsuo** [comment]
你这个应该是选了两个数据一个维度吧？应该把 order_src 放到维度栏里吧？
