### ISSUE TITLE
请教一个自适应的问题

### ISSUE THREAD

**Issue by whenTheMorningDark** [dongsuo/vue-data-board#14]
如果我在项目，用的是echart，请问如何实现伸缩框后，让里面的图标自适应呢？

**Comment by dongsuo** [comment]
echart 有一个 resize() 的方法，监听伸缩框的变化，然后调用这个方法就好了

**Comment by whenTheMorningDark** [comment]
> echart 有一个 resize() 的方法，监听伸缩框的变化，然后调用这个方法就好了

嗯嗯 谢谢了 问题已经解决了。
