### ISSUE TITLE
index.html  favicon的URL出错 

### ISSUE THREAD

**Issue by adam429** [dongsuo/vue-data-board#16]
index.html的代码里，favicon是这样写的

`<link rel="icon" href="<%= BASE_URL %>favicon.ico">`

这个BASE_URL没有被正确转化，在浏览器里面，还是以<%= BASE_URL %>的形式显示

报错

> URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
>     at decodeURIComponent (<anonymous>)
>     at decode_param (/Users/adam429/Projects/vue-data-board/node_modules/express/lib/router/layer.js:172:12)

浏览器的Developer模式看到的

![image](https://user-images.githubusercontent.com/48518/63632273-a98b8380-c665-11e9-81d8-c456bf48cbed.png)

**Comment by dongsuo** [comment]
我这里是正常的，这个问题是你本地出现的吧？我没能重现。

**Comment by dongsuo** [comment]
本地启动的时候, 路径应该是这个: http://localhost:8080/vue-data-board/ 
如果你没有改配置项的话……
