### ISSUE TITLE
请教npm run dev missing 问题

### ISSUE THREAD

**Issue by yebidaxiong** [dongsuo/vue-data-board#18]
npm run dev 报错：missing script:dev, run install 之后在package.json里 script没有生成dev，求解

**Comment by dongsuo** [comment]
不好意思，文档写错了，应该是 `npm run serve`

**Comment by yebidaxiong** [comment]
> 不好意思，文档写错了，应该是 `npm run serve`

我是前端小白，请教一下，我run serve之后显示network error是因为哪里没有配置正确呢？
