### ISSUE TITLE
编辑现有图表，部分会有错误提示

### ISSUE THREAD

**Issue by yehonghao** [dongsuo/vue-data-board#22]
编辑现有图表，部分会有错误提示。如测试账号下，北京仪表盘，新增订单渠道来源分布 图表。

dbbychart接口作用是什么？ 是不是已经弃用了

**Comment by dongsuo** [comment]
没有弃用，用来获取已绑定某chart 的 dashboard 列表，避免dashboard 下重复添加同一 chart，这里应该是后端代码有 bug

**Comment by dongsuo** [comment]
fixed.
