### ISSUE TITLE
sql表在哪里？能不能导出一份表及数据，方便搭建环境

### ISSUE THREAD

**Issue by coolxv** [dongsuo/vue-data-board#26]

**Comment by dongsuo** [comment]
https://github.com/dongsuo/leancloud-server/issues/7

**Comment by dongsuo** [comment]
https://github.com/dongsuo/py_vislib
用 Python 写了一个简单的后端项目，里面有开发数据库的配置，另外文档也更新了一份，在 [docs.vislib.best](https://docs.vislib.best) 可以看到
