### ISSUE TITLE
关于拖动

### ISSUE THREAD

**Issue by cangyu1993** [dongsuo/vue-data-board#3]
这个拖动是怎么实现的呢

**Comment by dongsuo** [comment]
拖拽和布局部分是 vue-grid-layout 和 vuedraggable这两个库。

**Comment by dongsuo** [comment]
拖拽和布局部分是 vue-grid-layout 和 vuedraggable这两个库。

**Comment by cangyu1993** [comment]
哦哦哦，研究研究，谢谢大牛
