### ISSUE TITLE
为什么仪表盘的布局和分享之后的布局不一致？

### ISSUE THREAD

**Issue by shuitai** [dongsuo/vue-data-board#41]
为什么仪表盘的布局和分享之后的布局不一致？
分享之后的图表，是每个一行，和仪表盘的位置不太一样

**Comment by zhenghao35791** [comment]
请问这个问题能解决吗

**Comment by dongsuo** [comment]
Fixed.
https://github.com/dongsuo/vue-data-board/pull/42/files#diff-5fdf7297c1f182b9f9db7c2c5ec893fdR19
