### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by zzmbulldog** [dongsuo/vue-data-board#45]
请问按照步骤安装后，不管是新建账号还是用默认账号都登录失败，会是什么原因呢？

**Comment by dongsuo** [comment]
可以把报错信息贴出来

**Comment by zzmbulldog** [comment]
![image](https://user-images.githubusercontent.com/40566786/90997295-c00b4880-e5f3-11ea-8a9c-92d8eaff9d01.png)
![image](https://user-images.githubusercontent.com/40566786/90997305-ca2d4700-e5f3-11ea-984d-a6f8fbf1818d.png)
![image](https://user-images.githubusercontent.com/40566786/90997310-ce596480-e5f3-11ea-95dc-ec7b127019da.png)

**Comment by zzmbulldog** [comment]
![image](https://user-images.githubusercontent.com/40566786/90998060-c3073880-e5f5-11ea-83d2-1aaf8ebd3d9a.png)
这里请求不传username和password，不能取到吧？不懂py....

**Comment by zzmbulldog** [comment]
这里请求不传username和password，不能取到吧？不懂py....
![image](https://user-images.githubusercontent.com/40566786/90998163-006bc600-e5f6-11ea-9f21-2c17b4dbe9d4.png)
@dongsuo

**Comment by zzmbulldog** [comment]
这里请求不传username和password，不能取到吧？不懂py....

@csrf_exempt
def userInfo(request):
    if request.user.is_authenticated:
        username = request.user.get_username()
        return JsonResponse({'code': 20000, 'data': {'username': username}})
    else:
        return JsonResponse({'code': 40000, 'message': 'Please login'})

@dongsuo

**Comment by dongsuo** [comment]
猜测是跨域问题？cookie没有塞成功？

**Comment by zyyquanquan** [comment]
我也遇到了同样的问题，有解决办法了嘛

**Comment by zyyquanquan** [comment]
可以注册成功，登录不了

**Comment by zyyquanquan** [comment]
浏览器兼容问题，换一个浏览器就登录成功了

**Comment by JoffreyN** [comment]
谷歌浏览器不行

**Comment by JoffreyN** [comment]
地址栏输入：chrome://flags/
找到"SameSite by default cookies"和"Cookies without SameSite must be secure"
将上面两项设置为 Disable

**Comment by jinyang1994** [comment]
将Python中设置Cookie Samesite的部分，从`None`改为`Strict`

**Comment by dongsuo** [comment]
This issue is because Chrome and many other browsers changed their cookies policy.  
fixed at: https://github.com/dongsuo/py_vislib/commit/b9738d36d84dc0f243d4f92ea2da04191e38b954
