### ISSUE TITLE
缺少代码

### ISSUE THREAD

**Issue by xdwxls** [dongsuo/vue-data-board#63]
你好，vue.config.js 中 有  proxy: {
      '^/api': {
        target: 'http://localhost:8000'
      }
    } 代码，
导致npm run serve，无法运行，请问下这个后端模拟数据项目地址有吗？

**Comment by xdwxls** [comment]
找到办法了，线上api 改成本地的

**Comment by dongsuo** [comment]
看文档

**Comment by xdwxls** [comment]
https://v11nlab.com/   你的线上网站打不开

**Comment by xdwxls** [comment]
https://v11nlab.com/  你的线上地址，测试账号，登录不了
有报错：Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
